export const USER_PICKER_TYPE = {
  C2C_CONVERSATION: 1,

  CREATE_GROUP: 2,

  REMOVE_GROUP_MEMBER: 3,

  INVITE_GROUP_MEMBER: 4,

  PROMOTE_ADMIN: 5,

  DEMOTE_ADMIN: 6,

  MUTE_GROUP_MEMBER: 7,

  UNMUTE_GROUP_MEMBER: 8,

  TRANSFER_GROUP_OWNER: 9,

  SELECT_GROUP_MEMBER: 10,

  SELECT_GROUP_AT_USER: 11,
} as const

export type UserPickerType = typeof USER_PICKER_TYPE[keyof typeof USER_PICKER_TYPE]
