export const demoEn = {
  demo: {
    login: {
      title: 'Tuikit Chat',
      subtitle: 'Sign in with your Tencent Cloud IM account',
      sdkAppIdLabel: 'SDKAppID',
      userIdLabel: 'UserID',
      userIdPlaceholder: 'Enter user ID',
      userIdEmpty: 'Please enter UserID',
      loginButton: 'Sign in',
      switchingAccount: 'Failed to switch account',
      loginFailed: 'Sign in failed',
      userSigFailed: 'Failed to generate UserSig',
      unknownError: 'Unknown error',
      tip: 'Tip',
      help: 'Tip: UserSig is generated by debug/GenerateTestUserSig.js with the SDKAppID\'s SecretKey (for local debug only).',
    },
    tabBar: {
      message: 'Messages',
      relation: 'Contacts',
    },
    language: {
      label: 'Language',
      system: 'Follow system',
      zhCN: '简体中文',
      en: 'English',
      currentChanged: 'Switched to {{name}}',
    },
    screens: {
      conversationList: {
        title: 'Messages',
        searchEntryPlaceholder: 'Search',
        menu: {
          c2c: 'Start chat',
          createGroup: 'Create group',
        },
      },
      contactList: {
        title: 'Contacts',
        searchEntryPlaceholder: 'Search',
        menu: {
          addFriend: 'Add friend',
          addGroup: 'Add group',
        },
      },
      addFriend: {
        title: 'Add friend',
      },
      addGroup: {
        title: 'Add group',
        joinedAlready: 'Already joined this group',
      },
      blackList: {
        title: 'Blocklist',
      },
      createGroup: {
        title: 'Create group',
      },
      friendApplicationList: {
        title: 'New contacts',
      },
      groupApplicationList: {
        title: 'Group notifications',
      },
      groupList: {
        title: 'My groups',
      },
      groupManagement: {
        title: 'Group management',
      },
      groupMemberList: {
        title: 'Group members',
      },
      groupTypeInfo: {
        title: 'Group type',
      },
      setRemark: {
        title: 'Edit remark',
      },
      userFilter: {
        title: 'Filter users',
      },
      applicationVerify: {
        title: {
          friend: 'Apply to add friend',
          group: 'Apply to join group',
        },
      },
      contactInfo: {
        title: {
          addFriend: 'Add friend',
          newContact: 'New contact',
          friend: 'Friend details',
          default: 'Contact details',
        },
      },
      search: {
        placeholder: 'Search contacts, groups, messages',
      },
      searchInConversation: {
        placeholder: 'Search messages',
      },
      userPicker: {
        title: {
          default: 'Select contacts',
          selectGroupAtUser: 'Select @ users',
        },
      },
      chatSetting: {
        title: {
          c2c: 'Settings',
          c2cProfile: 'Profile',
          group: 'Group settings',
        },
      },
      chat: {
        title: {
          default: 'Chat',
          group: 'Group chat',
        },
        notInGroup: 'You are no longer in the group',
        notInGroupTip: 'Tip',
      },
    },
  },
} as const
