
export enum UserPickerType {
  INVITE_GROUP_MEMBER = 4,
  REMOVE_GROUP_MEMBER = 3,
  TRANSFER_GROUP_OWNER = 9,
  PROMOTE_ADMIN = 5,
  DEMOTE_ADMIN = 6,
  MUTE_GROUP_MEMBER = 7,
  UNMUTE_GROUP_MEMBER = 8,
}
